### ISSUE TITLE
[BUG] Failed to handle HashMap from canister

### ISSUE THREAD

**Issue by kentsday** [edjCase/ICP.NET#52]
version 2.0.8

candid
```
service : () -> {
    get_wasm_info : () -> (vec record {
        text;
        text
    }) query;
}
```

gen code

```cs
public class Arg0ItemRecord
{
    [CandidName("0")] public string F0 { get; set; }

    [CandidName("1")] public string F1 { get; set; }

    public Arg0ItemRecord(string f0, string f1)
    {
        this.F0 = f0;
        this.F1 = f1;
    }

    public Arg0ItemRecord()
    {
    }
}
```

but
![image](https://user-images.githubusercontent.com/92845901/227192287-5bf70de9-8568-48e8-bfe0-5c0b06077d20.png)

![image](https://user-images.githubusercontent.com/92845901/227192984-fabb4cea-7a4c-465f-94e6-3d45f09cf31e.png)

then

```
System.Collections.Generic.KeyNotFoundException: The given key '0(48)' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at EdjCase.ICP.Candid.Mapping.Mappers.RecordMapper.Map(CandidValue value, CandidConverter converter)
   at EdjCase.ICP.Candid.CandidConverter.ToObject(Type objType, CandidValue value)
   at EdjCase.ICP.Candid.Mapping.Mappers.VectorMapper.<>c__DisplayClass16_0.<Map>b__0(CandidValue v)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at EdjCase.ICP.Candid.Mapping.DefaultMapperFactory.<>c__DisplayClass2_0.<BuildTypeInfo>b__35(IEnumerable`1 v, CandidConverter options)
   at EdjCase.ICP.Candid.Mapping.Mappers.VectorMapper.Map(CandidValue value, CandidConverter converter)
   at EdjCase.ICP.Candid.CandidConverter.ToObject(Type objType, CandidValue value)
   at EdjCase.ICP.Candid.CandidConverter.ToObject[T](CandidValue value)
   at EdjCase.ICP.Candid.Models.CandidTypedValue.ToObject[T](CandidConverter converter)
   at EdjCase.ICP.Candid.Models.CandidArg.ToObjects[T1](CandidConverter candidConverter)
   at xxxxxApiClient.cs:line 69
```

**Comment by Gekctek** [comment]
Yikes. Not sure how that happened. Was treating the 0 and 1 as names vs id/hashes.
Try this out
https://github.com/edjCase/ICP.NET/releases/tag/2.1.0

Let me know if that fixes it for you

**Comment by kentsday** [comment]
it works with 2.1.0 packages, thx !
